name: Link Check

on:
  pull_request:
    paths:
    - ".github/workflows/link-check.yml"
    - ".markdown-link-check.json"
    - "link-check.js"
    - "package*.json"
    - "**/*.md"

  push:
    branches-ignore:
    - "dependabot/**"
    paths:
    - ".github/workflows/link-check.yml"
    - ".markdown-link-check.json"
    - "link-check.js"
    - "package*.json"
    - "**/*.md"

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run link checks
        run: npm run link-check
